packages:
    # All packages in direct subdirs of packages/
    - "packages/*"
    # All packages in subdirs of components/
    - "apps/*"
    # Exclude files from package builds
    - "!**/test/**"
    - "!**/.next/**"
    - "!**/dist/**"
